FROM docker.io/library/archlinux:latest
RUN pacman-key --init
RUN pacman -Sy --noconfirm archlinux-keyring && pacman -Syyu --noconfirm 
RUN pacman -Sy --needed --noconfirm dbeaver \
  mariadb-clients \
  base-devel \
  git

# user
RUN useradd builduser -m
RUN passwd -d builduser
RUN printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
USER builduser

# paru
WORKDIR /tmp
RUN git clone https://aur.archlinux.org/paru-bin.git && cd paru-bin && makepkg -si --noconfirm
RUN rm -rf /tmp/paru-bin
RUN paru -S --noconfirm mongodb-tools-bin
RUN paru -Sc --noconfirm

USER root
ENV GTK_THEME=adwaita
COPY ./post-install.sh /usr/local/bin/post-install.sh
