FROM ghcr.io/fearlix-srl/base:latest
ENV GOPATH=/usr/local/lib/go
ENV GOCACHE=/var/cache/go
ENV GOENV=/usr/lib/golang/go.env
ENV GOMODCACHE=${GOPATH}/pkg/mod
RUN mkdir -p ${GOPATH} ${GOCACHE} ${GOMODCACHE}
RUN chown -R builduser:builduser ${GOCACHE} ${GOPATH} ${GOMODCACHE}
RUN chmod -R 755 ${GOCACHE} ${GOPATH} ${GOMODCACHE}
RUN dnf install -y \
    golang && \
    dnf clean all
USER builduser
RUN go telemetry off
RUN go install -v github.com/go-delve/delve/cmd/dlv@latest

# Post Install
COPY ./post-install.sh /usr/local/bin/post-install.sh
