FROM docker.io/library/ubuntu:22.04

# user
# RUN useradd builduser -m
# RUN passwd -d builduser
# RUN printf 'builduser ALL=(ALL) ALL\n' | tee -a /etc/sudoers
# USER builduser

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt update && apt upgrade -y
RUN apt install -y lsb-release \
  wget \
  gnupg \
  locales \
  software-properties-common \
  curl

# gazebo
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list
RUN apt update
RUN apt install -y ignition-fortress

# locale
RUN locale-gen en_US en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG=en_US.UTF-8

#ros
RUN add-apt-repository universe
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" > /etc/apt/sources.list.d/ros2.list
RUN apt update
RUN apt install -y ros-humble-desktop ros-dev-tools
RUN rosdep init

RUN echo "source /opt/ros/humble/setup.bash" > /etc/profile.d/ros.sh
