FROM registry.fedoraproject.org/fedora-toolbox:42

RUN dnf copr enable atim/lazygit -y

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
  echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo

RUN dnf install -y neovim \
  ripgrep \
  code \
  lazygit \
  alacritty \
  chromium && \
  dnf clean all

RUN wget https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz -O - | tar -xz -C /usr/local/bin/

RUN wget https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.tar.xz -O - | tar -xJ -C /usr/share/fonts

# user
RUN useradd builduser -m && \
  passwd -d builduser && \
  printf 'builduser ALL=(ALL) NOPASSWD:ALL\n' | tee -a /etc/sudoers

# Podman
ENV DOCKER_HOST=unix:///run/user/1000/podman/podman.sock
RUN echo "alias podman='distrobox-host-exec podman'" > /etc/profile.d/podman.sh

