name: build-base

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  base:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: base

  database:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: database

  flutter:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: base
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: flutter

  go:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: base
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: go

  node:
    permissions:
      contents: read
      packages: write
      id-token: write
    needs: base
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: node
