name: build-base

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  base:
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: base

  flutter:
    needs: base
    uses: ./.github/workflows/_build-image.yml
    with:
      image-name: flutter
